### PR TITLE
Fix NW configuration for Ember 1.13.x

### PR DESCRIPTION
**Pull request by brzpegasus**
Ember 1.13.x checks for the existence of `process` to determine if it is running in Node (probably for Fastboot). This can result in errors trying to load an Ember app in NW.js.

Changes:

* The shim script will now delete `window.process` then restore it at the end.
* Restoring NW.js variables on the window `load` event would not guarantee to run when it should. The shim is now split between 2 scripts: `shim-head.js` and `shim-footer.js`, both of which are injected into the page via the `contentFor` hooks.
* The `vendor/node-webkit/*.js` blueprint files are no longer necessary and have been removed.
* The `reload.js` file was moved from the blueprint to the addon's `client/node-webkit/` folder and will be managed entirely by the addon itself. The consuming app won't have a copy of it laying around.
* The addon now sets a `process.env.EMBER_CLI_NW = true` for all of its commands. This ensures that custom build steps only execute for the correct environment.

### CODE REVIEW

**Comment by rwjblue** [comment]
I'd kinda like to fix this in Ember itself also.  I believe there is an open issue in the Ember repo for it (can't recall from whom though).

**Comment by brzpegasus** [comment]
Ah, yes, it must be this [issue](https://github.com/emberjs/ember.js/issues/11679). Having it fixed in Ember would definitely be great. I wonder if in addition to verifying that `process` exists, we should also verify that `window` does not, before concluding we're in Node.

**Comment by rwjblue** [comment]
Sounds great, would you mind testing that out locally and submitting a pull request to Ember?

**Comment by brzpegasus** [comment]
:+1:

**Comment by brzpegasus** [comment]
Pull requests that address this issue:

* **Ember:** [#11895](https://github.com/emberjs/ember.js/pull/11895)
* **RSVP:** [#398](https://github.com/tildeio/rsvp.js/pull/398)

**Pull request merged**
